version: "3.7"

services:

  mysql:
    image: mysql
    container_name: mysql5
    command: mysqld
    volumes:
      - ./db_data:/var/lib/mysql
    ports: 
      - 33060:3306
    hostname: mysql
    environment:
        DB_SERVER_PORT: 3306
        MYSQL_ROOT_PASSWORD: secret1
        MYSQL_USER: 'demo'
        MYSQL_PASSWORD: 'secret2'
        MYSQL_DB: 'demo'
  
  maven-app:
    container_name: maven-app
    image: maven-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
      - "mysql"
    command: [ "./mvnw", "spring-boot:run" ]
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/demo
      - spring.datasource.username=demo
      - spring.datasource.password=secret2
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.jpa.hibernate.ddl-auto = update

volumes:
  mysql-data:
    driver: local




